spring:
  cloud:
    gateway:
      routes:
        - id: voiture-route
          uri: http://localhost:8089/
          predicates:
            - Path=/api/voitures

        - id: client-route
          uri: http://localhost:8088/
          predicates:
            - Path=/api/clients

server:
  port: 8888
